name: Incremental Metadata Updates

on:
  schedule:
    - cron: "0 13 * * 2,4"  # Run Tuesday and Thursday at 1pm UTC (reduced frequency, better distribution)
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to consider as recent'
        required: false
        default: '14'
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  incremental-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better branch handling
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyGithub pyyaml
      
      - name: Run incremental metadata update
        run: |
          python scripts/incremental_metadata_update.py --recent-only --days ${{ github.event.inputs.days || 14 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_SCHOLAR_KEY: ${{ secrets.SEMANTIC_SCHOLAR_KEY }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      
      - name: Update data.json with incremental data
        run: python update_data_json.py --include-metadata
      
      - name: Validate data integrity
        run: |
          python scripts/verify_repo_metadata.py
          python scripts/verify_readme_content.py
      
      - name: Prepare changes
        id: prepare
        run: |
          # Setup git user identity
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the changed files
          git add data.json metadata/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            # Create a unique branch name with timestamp
            BRANCH_NAME="incremental-metadata-update-$(date +%Y%m%d-%H%M%S)"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.prepare.outputs.changes_detected == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: "Incremental metadata update"
          title: "Incremental metadata update"
          body: |
            ## Automated PR with incremental metadata updates
            
            This PR contains incremental updates to tool metadata that have been collected by the automated workflow.
            
            - Updated metadata for tools modified in the last ${{ github.event.inputs.days || 14 }} days
            - Regenerated data.json with the latest metadata
            - Validated data integrity
            
            Automated pull request created by the [Incremental Metadata Updates workflow](https://github.com/${{ github.repository }}/actions/workflows/incremental-updates.yml).
          branch: ${{ steps.prepare.outputs.branch_name }}
          base: main
      
      - name: Output PR URL
        if: steps.prepare.outputs.changes_detected == 'true'
        run: |
          if [[ -n "${{ steps.create-pr.outputs.pull-request-url }}" ]]; then
            echo "::notice::PR created successfully: ${{ steps.create-pr.outputs.pull-request-url }}"
          else
            echo "::warning::PR creation failed. You need to configure one of the following:"
            echo "::warning::1. A PAT_TOKEN secret with 'repo' scope"
            echo "::warning::2. Set the permissions in the workflow to: contents: write, pull-requests: write"
            echo "::notice::For now, you can create a PR manually at: https://github.com/$GITHUB_REPOSITORY/pull/new/${{ steps.prepare.outputs.branch_name }}"
          fi