name: Update Citation Data

on:
  workflow_dispatch:
    inputs:
      include_pubmed:
        description: 'Include PubMed citation data'
        type: boolean
        default: true
      skip_validation:
        description: 'Skip data validation steps'
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update-citation-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for better branch handling
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Update data.json with citation data
        run: |
          # Include all metadata types for comprehensive update
          ARGS="--include-metadata --include-bioinformatics --include-academic-impact"
          
          # Add PubMed if selected
          if [[ "${{ github.event.inputs.include_pubmed }}" == "true" ]]; then
            ARGS="${ARGS} --include-pubmed"
          fi
          
          # Run the update command
          python update_data_json.py ${ARGS}
        
      - name: Validate data integrity
        if: ${{ github.event.inputs.skip_validation != 'true' }}
        run: |
          python scripts/verify_repo_metadata.py
          python scripts/verify_readme_content.py
        
      - name: Prepare changes
        id: prepare
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            # Create a unique branch name with timestamp
            BRANCH_NAME="update-citation-data-$(date +%Y%m%d-%H%M%S)"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.prepare.outputs.changes_detected == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update data.json with citation improvements"
          title: "Update citation data with CrossRef fallback"
          body: |
            ## Citation Data Update
            
            This PR updates the data.json file with improved citation handling.
            
            Changes include:
            - Updated citation counts with CrossRef fallback mechanism
            - Added indicators for CrossRef data sources in UI
            - Fixed tools showing zero citations when they should have citation data
            
            Generated automatically by GitHub Actions workflow.
          branch: ${{ steps.prepare.outputs.branch_name }}
          base: main
          
      - name: Output PR URL
        if: steps.prepare.outputs.changes_detected == 'true'
        run: |
          if [[ -n "${{ steps.create-pr.outputs.pull-request-url }}" ]]; then
            echo "::notice::PR created successfully: ${{ steps.create-pr.outputs.pull-request-url }}"
          else
            echo "::warning::PR creation failed. Please check repository permissions."
            echo "::notice::For now, you can create a PR manually at: https://github.com/$GITHUB_REPOSITORY/pull/new/${{ steps.prepare.outputs.branch_name }}"
          fi