name: Update Repository Information

on:
  schedule:
    # Run weekly on Sunday at 08:00 UTC (well after repo testing and cache maintenance)
    - cron: "0 8 * * 0"
    # Run enhanced metadata on 2nd of each month (after workflow coordination on 1st)
    - cron: "0 8 2 * *"
    # Run bioinformatics metadata on 16th of each month (spreading load)
    - cron: "0 8 16 * *"
    # Run academic impact metadata on 5th of each month (after PubMed on 4th)
    - cron: "0 6 5 * *"
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update to run'
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - enhanced
          - bioinformatics
          - academic_impact
          - all

jobs:
  update-repos:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * 0' || github.event_name == 'workflow_dispatch' && (github.event.inputs.update_type == 'basic' || github.event.inputs.update_type == 'all')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
      
      - name: Update repository information
        run: python update_check.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verify README content
        run: python scripts/verify_readme_content.py
      
      - name: Update data.json
        run: python update_data_json.py
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md data.json repo_updates.json update_check.log
          git diff --staged --quiet || git commit -m "Update repository information"
          git push

  enhance-metadata:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 1 * *' || github.event_name == 'workflow_dispatch' && (github.event.inputs.update_type == 'enhanced' || github.event.inputs.update_type == 'all')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
      
      - name: Collect enhanced metadata
        run: python scripts/enhance_metadata.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update data.json with enhanced metadata
        run: python update_data_json.py --include-metadata
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json metadata/
          git diff --staged --quiet || git commit -m "Update enhanced metadata"
          git push

  bioinformatics-metadata:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 15 * *' || github.event_name == 'workflow_dispatch' && (github.event.inputs.update_type == 'bioinformatics' || github.event.inputs.update_type == 'all')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub pyyaml
      
      - name: Collect bioinformatics metadata
        run: python scripts/bioinformatics_metadata.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update data.json with bioinformatics metadata
        run: python update_data_json.py --include-metadata --include-bioinformatics
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json metadata/
          git diff --staged --quiet || git commit -m "Update bioinformatics metadata"
          git push

  warm-cache:
    if: |
      github.event_name == 'schedule' && (github.event.schedule == '0 0 1 * *' || github.event.schedule == '0 0 5 * *') ||
      github.event_name == 'workflow_dispatch' && (github.event.inputs.update_type == 'academic_impact' || github.event.inputs.update_type == 'all')
    uses: ./.github/workflows/cache-warming.yml
    with:
      scope: 'important'
    secrets: inherit

  academic-impact-metadata:
    runs-on: ubuntu-latest
    needs: warm-cache
    if: |
      github.event_name == 'schedule' && github.event.schedule == '0 0 5 * *' || 
      github.event_name == 'workflow_dispatch' && (github.event.inputs.update_type == 'academic_impact' || github.event.inputs.update_type == 'all')
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub pyyaml matplotlib networkx
      
      - name: Check for recent PubMed update
        id: check_pubmed
        run: |
          # Check if PubMed data was updated in the last 48 hours
          PUBMED_UPDATED=$(git log --since="48 hours ago" --oneline | grep "Update PubMed citation information" | wc -l)
          if [ $PUBMED_UPDATED -gt 0 ]; then
            echo "Recent PubMed update found, will use existing data"
            echo "pubmed_is_current=true" >> $GITHUB_OUTPUT
          else
            echo "No recent PubMed update found"
            echo "pubmed_is_current=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run PubMed collection if needed
        if: steps.check_pubmed.outputs.pubmed_is_current != 'true'
        run: |
          echo "Running PubMed citation collection as prerequisite for academic impact analysis"
          python scripts/pubmed_citations.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      
      - name: Collect academic impact metadata
        run: python scripts/academic_impact.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_SCHOLAR_KEY: ${{ secrets.SEMANTIC_SCHOLAR_KEY }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      
      - name: Generate citation reports
        run: python scripts/citation_report.py
      
      - name: Validate data integrity
        run: |
          python scripts/verify_repo_metadata.py
          python scripts/verify_readme_content.py
        
      - name: Update data.json with academic impact metadata
        run: |
          # Include PubMed data in the update
          python update_data_json.py --include-metadata --include-bioinformatics --include-academic-impact --include-pubmed
      
      - name: Prepare changes
        id: prepare
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json metadata/ reports/ citations.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.prepare.outputs.changes_detected == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update academic impact metadata and citation reports
          title: Update academic impact metadata and citation reports
          body: |
            ## Automated PR with academic impact data updates
            
            This PR updates the academic impact metadata and citation reports based on the latest analysis.
            
            Changes include:
            - Updated academic impact metadata
            - Updated citation reports
            - Updated data.json with latest academic impact information
            
            Generated automatically by GitHub Actions workflow.
          branch: academic-impact-${{ github.run_id }}
          base: main
          delete-branch: false
      
      - name: PR Creation Result
        if: steps.prepare.outputs.changes_detected == 'true'
        run: |
          if [[ -n "${{ steps.create-pr.outputs.pull-request-url }}" ]]; then
            echo "::notice::PR created successfully: ${{ steps.create-pr.outputs.pull-request-url }}"
          else
            echo "::warning::PR creation failed. You may need to enable 'Allow GitHub Actions to create and approve pull requests' in repository Settings > Actions > General"
          fi